export 'package:yandex_maps_mapkit/src/directions/driving/annotation.dart'
    hide
        DrivingAnnotationContainerExtension,
        DrivingToponymPhraseImpl,
        DrivingAnnotationSchemeIDImpl,
        DrivingAnnotationSchemeIDContainerExtension,
        DrivingActionMetadataImpl,
        DrivingUturnMetadataNative,
        DrivingActionMetadataNative,
        DrivingAnnotationImpl,
        DrivingActionMetadataContainerExtension,
        DrivingToponymPhraseContainerExtension,
        DrivingTurnMetadataContainerExtension,
        DrivingTurnMetadataNative,
        DrivingExitMetadataNative,
        DrivingUturnMetadataContainerExtension,
        DrivingLeaveRoundaboutMetadataNative,
        DrivingLeaveRoundaboutMetadataContainerExtension,
        DrivingExitMetadataContainerExtension;
